version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - "doxygen"
    - "cmake"
  jobs:
    pre_build:
      - "cmake -S . -B build -DBUILD_DOCUMENTATION=ON"
      - "cmake --build build --target Doxygen"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
